import { Header } from "@/widgets/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/assets/styles/normalize.css";
import "@/assets/styles/reset.css";
import { MainContainer } from "@/shared/containers/main";
import { StageBarProvider } from "@/widgets/stage-bar-provider";
import { ContentContainer } from "@/shared/containers/content";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Hint Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainContainer>
          <Header />
          <StageBarProvider>
            <ContentContainer>{children}</ContentContainer>
          </StageBarProvider>
        </MainContainer>
      </body>
    </html>
  );
}
