import { Header } from "@/widgets/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/assets/styles/normalize.css";
import "@/assets/styles/reset.css";
import { MainContainer } from "@/shared/containers/main";

const inter = Inter({ subsets: ["latin"], weight: [] });

export const metadata: Metadata = {
  title: "Hint Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainContainer>
          <Header />
          {children}
        </MainContainer>
      </body>
    </html>
  );
}
